Base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from apps.usuarios.views import Login,Logout
from django.conf.urls.static import static
from django.contrib.auth.views import login

urlpatterns = [
   path('admin/', admin.site.urls),
   path('login/', Login.as_view()),
   path('logout/', Logout.as_view()),
   path('',include('apps.almacen.urls', namespace='almacen')),
   url(r'^usuarios/',include('apps.usuarios.urls',namespace='usuarios')),
   url(r'^productos/',include('apps.productos.urls',namespace='productos')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
admin.site.site_header = 'Administrador BACKEND Real Star'
admin.site.site_title= "Interface web del administrador"

apps/productos/urls.py
from django.conf.urls import url
from .views import *
app_name='productos'
urlpatterns = [
 	url(r'^$', Index.as_view(),name='index'),
    url(r'^listar$', ListarProductos.as_view(),name='Listar_Productos'),
    url(r'^eliminar/(?P<pk>\d+)/$', EliminarProducto.as_view(),name='Eliminar_Producto'),
    #url(r'^registrar$',RegistrarProducto.as_view(),name='Registrar_Producto'),
    #url(r'^editar/(?P<pk>\d+)/$',EditarProducto.as_view(),name='Editar_Producto'),
    url(r'^registrar$',RegistrarProducto.as_view(),name='Registrar_Producto'),
    url(r'^editar/(?P<pk>\d+)',Editar_Producto.as_view(),name='Editar_Producto'),
    url(r'^categoria$',Categorias.as_view(),name='Categorias'),
    url(r'editar_categoria/(\d+)/$',Editar_Categoria,name='Editar_Categoria'),
    url(r'^eliminar_categoria/(?P<pk>\d+)/$', EliminarCategoria,name='Eliminar_Categoria')
]

apps/productos/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=15)
    def __str__(self):
        return  self.nombre

class UnidadMedicion(models.Model):
    nombre = models.CharField(max_length=20)
    def __str__(self):
        return self.nombre

class Producto(models.Model):
    codigo = models.AutoField(primary_key=True, max_length=10)
    descripcion = models.CharField(max_length=50, blank=True, null=True)
    categoria = models.ForeignKey(Categoria,blank=True,null=True, on_delete=models.PROTECT)
    stock_minimo = models.IntegerField(blank=True, null=True)
    def __str__(self):
        return self.descripcion


class ProductoMedida(models.Model):
    id_unidad = models.ForeignKey(UnidadMedicion,blank=True,null=True, on_delete=models.PROTECT)
    codigo_producto = models.ForeignKey(Producto,blank=True,null=True, on_delete=models.PROTECT)
    valor = models.DecimalField('Valor S/.',max_digits=4,decimal_places=2)

    """class Meta:
        unique_together = (("id_unidad", "codigo_producto"),)"""

apps/productos/forms.py
from django import forms
from django.forms import ModelForm, formset_factory, inlineformset_factory
from .models import Producto,Categoria,UnidadMedicion,ProductoMedida
from apps.general import mensaje_aplicacion


class ProductoForm(forms.ModelForm):
    descripcion = forms.CharField(max_length=50,
                                  widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Descripción'}),
                                  label="Descripcion")
    categoria = forms.ModelChoiceField(queryset=Categoria.objects.all(),
                                       widget=forms.Select(attrs={'class':'form-control','placeholder':'Categoría'}),
                                       label="Categoria",empty_label="Seleccione una categoria")
    stock_minimo = forms.IntegerField(widget=forms.NumberInput(attrs={'class':'form-control',
                                                                      'placeholder':'Stock mínimo'}),
                                      label="Stock Minimo")
    def clean_stock(self):
        stock_minimo = self.cleaned_data.get("stock_minimo")
        if stock_minimo < 0:
            raise forms.ValidationError(mensaje_aplicacion.STOCK_MUST_BE_POSITIVE)
        return stock_minimo
    class Meta:
        model = Producto
        fields = ('descripcion','categoria','stock_minimo',)

class UnidadProductoForm(forms.ModelForm):
    id_unidad = forms.ModelChoiceField(queryset=UnidadMedicion.objects.all(),
                                       widget=forms.Select(attrs={'class':'form-control'}),
                                       label="Valor",
                                       empty_label='Seleccione una unidad de medida')
    valor = forms.DecimalField(max_digits=4,decimal_places=2,
                                      widget=forms.NumberInput(attrs={'class':'form-control',
                                                                      'placeholder':'Valor S/.'}),
                                      label="Valor")
    def clean_valor(self):
        valor = self.cleaned_data.get("valor")
        if valor < 0:
            raise forms.ValidationError(mensaje_aplicacion.VALOR_MUST_BE_POSITIVE)
        return valor
    class Meta:
        model = ProductoMedida
        fields = ['id_unidad','valor',]

UnidadProductoFormSet = inlineformset_factory(Producto,ProductoMedida,UnidadProductoForm, extra=1, max_num=2,)
UnidadProductoFormSetEdit = inlineformset_factory(Producto,ProductoMedida,UnidadProductoForm, extra=0, max_num=2,min_num=1,can_delete=True)

class CategoriaForm(forms.ModelForm):
    nombre = forms.CharField(max_length=15,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Nueva categoria','required':True}),label="Nombre")
    class Meta:
        model = Categoria
        fields = ['nombre',]

apps/productos/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views.generic import View, CreateView, ListView, UpdateView, DeleteView
from Base.mixins import SuccessMessageMixin
from django.http import HttpResponse,HttpResponseRedirect
from .forms import *
from .models import *
from django.template.context import RequestContext
from itertools import chain
class LoginRequiredMixin(object):
    u"""Ensures that user must be authenticated in order to access view."""

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)

class Index(LoginRequiredMixin, View):
    template_name = 'productos/index.html'
    def get(self, request):
        return render(request, self.template_name)

    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            return HttpResponseRedirect('/success/')

        return render(request, self.template_name, {'form': form, 'error': 'Verifique los datos ingresados'})

class ListarProductos(LoginRequiredMixin,ListView):
    #Q1=Producto.objects.prefetch_related('ProductoMedida_set')
    queryset = Producto.objects.prefetch_related('productomedida_set').all()
    #queryset = ProductoMedida.objects.prefetch_related('codigo_producto').all()
    template_name = 'productos/listar_productos.html'
class EliminarProducto(SuccessMessageMixin,DeleteView):

    model = Producto
    success_url = '/productos/listar'
    template_name = 'productos/confirm_delete_producto.html'
    success_message = 'El producto fue eliminado correctamente'

class RegistrarProducto(LoginRequiredMixin,View,SuccessMessageMixin):
    template_name = 'productos/nuevo_producto.html'
    def get(self, request):

        producto_form = ProductoForm
        unidad_producto_formset = UnidadProductoFormSet(prefix='formset')
        return render(request,self.template_name,locals())
    def post(self,request):
        producto_form = ProductoForm(request.POST)
        unidad_producto_formset = UnidadProductoFormSet(request.POST,prefix='formset')
        if producto_form.is_valid() and unidad_producto_formset.is_valid() :
            producto = producto_form.save()
            unidad_producto_formset.instance = producto
            unidad_producto_formset.save()
            success_message = 'Los datos se actualizaron correctamente'
            return redirect('/productos/listar')
        else:
            producto_form = ProductoForm(request.POST)
            unidad_producto_formset = UnidadProductoFormSet(request.POST,prefix='formset')
            return render(request,self.template_name,locals())


class Editar_Producto (LoginRequiredMixin,View, SuccessMessageMixin):

    template_name = 'productos/editar_producto.html'
    # unidad_producto_formset = UnidadProductoFormSet

    def get(self, request,*args, **kwargs):
        producto = get_object_or_404(Producto,pk=self.kwargs['pk'])
        producto_form = ProductoForm(instance=producto)
        unidad_producto_formset = UnidadProductoFormSetEdit(prefix='formset', instance=producto)
        return render(request,self.template_name,locals())

    def post(self, request,*args,**kwargs):
        producto = get_object_or_404(Producto,pk=self.kwargs['pk'])
        producto_form = ProductoForm(request.POST,instance=producto)
        unidad_producto_formset = UnidadProductoFormSetEdit(request.POST,instance=producto,prefix='formset')

        if producto_form.is_valid() and unidad_producto_formset.is_valid():
            producto = producto_form.save()
            unidad_producto_formset.save()
            success_message = 'Los datos se actualizaron correctamente'
            return redirect('/productos')

        return render(request,self.template_name,locals())


class Categorias(View,SuccessMessageMixin):
    template_name = 'productos/categorias.html'
    success_message = 'Los datos se actualizaron correctamente'
    def get(self,request, *args, **kwargs):
        categoria = Categoria.objects.all()
        form = CategoriaForm
        return render(request,self.template_name,locals())
    def post(self,request):
        form = CategoriaForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/productos/categoria")
        else:
            return render(request, self.template_name, {'form': form, 'error': 'Verifique los datos ingresados'})


def Editar_Categoria(request,id):
    cat = Categoria.objects.get(pk=id)
    if request.POST:
        form = CategoriaForm(request.POST,instance=cat)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/productos/categoria")
        else:
            return render(request,'productos/categorias.html', {'form': form, 'error': 'Verifique los datos ingresados'})
    else:
        form = CategoriaForm(instance=cat)
        categoria = Categoria.objects.all()
        editar = {"editar":True}
        return render(request,'productos/categorias.html',locals())

 

class EliminarCategoria(SuccessMessageMixin,DeleteView):

    model = Categoria
    success_url = '/productos/categoria'
    template_name = 'productos/confirm_delete_categoria.html'
    success_message = 'El producto fue eliminado correctamente'

templates/productos/categorias.html
{% extends 'base.html' %}


{%  block breadcrumb %}
     <ol class="breadcrumb">
        <li ><a href="{%  url 'almacen:index' %}">Inicio</a></li>
        <li class="active"><a href="{%   url 'productos:index' %}">Productos</a></li>
        <li >Agregar categorias</li>
    </ol>
{% endblock %}


{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="container">
        <div class="row">

            <div class="panel form-panel panel-primary">
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-pencil"></span>
                    <span class="">AGREGAR NUEVA CATEGORIA</span>
                </div>
                <div class="panel-body">
{#                    <h3 class="text-left">Agregar categoria</h3>#}
                        <form enctype="multipart/form-data" method="post">
                            <div id="form">
                                {% csrf_token %}
                                    <div class="panel-body">
                                        <div class="input-group">
                                                <span class="input-group-addon glyphicon glyphicon-tag " ></span>
                                                {{form.nombre}}
                                            </div>

                                    </div>
                                    <div class="submit-row-cat col-xs-12">
                                        {% if editar %}
                                            <input  class ="col-sm-offset-3 col-sm-3 col-xs-6 btn btn-success btn-lg" type="submit" value="Guardar" />
                                        {% else %}
                                            <input  class ="col-sm-offset-3 col-sm-3 col-xs-6 btn btn-success btn-lg" type="submit" value="Registrar" />
                                        {% endif %}
                                        <a class ="col-sm-offset-1 col-sm-2  col-xs-6 btn btn-danger btn-lg"  href="{% url 'productos:index' %}">

                                            Volver

                                        </a>
                                    </div>
                            </div>
                        </form>
                    <div class="panel-body">
                    <div class="table-responsive">
                    <table class="table table-striped ">
                        {% load static from staticfiles %}
                        <thead>
                            <tr  align="center">
                                <td width="10%">Código</td>
                                <td width="60%">Categorias</td>
                                <td width="30%">Opciones</td>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in categoria %}
                            <tr valign="middle" class="{{forloop.counter|divisibleby:2|yesno:'even,odd'}}">
                                <td align="center">{{ item.pk }}</td>
                                <td align="center">{{ item.nombre }}</td>
                                <td align="center">
                                    <a href="{% url 'productos:Editar_Categoria' item.id %}"
                                       class="btn btn-info btn-delete">
                                        Editar
                                    </a>
                                    <a href="{% url 'productos:Eliminar_Categoria' item.id %}"  data-toggle="modal"
                                       data-target="#delete-modal" class="btn btn-danger btn-delete">
                                        Eliminar
                                    </a>


                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="modal fade" id="delete-modal">
        <div class="modal-dialog">
            <div class="modal-content">

            </div>
        </div>
    </div>


{% endblock %}

templates/productos/confirm_delete_categoria.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title"> Advertencia</h4>
</div>
<div class="modal-body">
    <form action="{% url 'productos:Eliminar_Categoria' object.id%}" class="text-center"method="post">{% csrf_token %}
        <p>Si elimina esta categoria, todos los productos de la Base de Datos asociados a ella serán eliminados, Esta seguro que desea eliminar {{ object.nombre }}  de la base de datos ?</p>
        <input class="btn btn-success" type="submit" value="Si, estoy seguro" />
    </form>
</div>

templates/productos/confirm_delete_producto.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title"> Advertencia</h4>
</div>
<div class="modal-body">
    <form action="{% url 'productos:Eliminar_Producto' object.codigo%}" class="text-center"method="post">{% csrf_token %}
        <p>Esta seguro que desea eliminar {{ object.descripcion }}  de la base de datos ?</p>
        <input class="btn btn-success" type="submit" value="Si, estoy seguro" />
    </form>
</div>

templates/productos/editar_producto.html
{% extends 'base.html' %}


{%  block breadcrumb %}
     <ol class="breadcrumb">
        <li ><a href="{%  url 'almacen:index' %}">Inicio</a></li>
        <li class="active"><a href="{%   url 'productos:index' %}">Productos</a></li>
        <li >Editar Productos</li>
    </ol>
{% endblock %}



{% block content %}
    <div class="container">
        <div class="row">
            <div class="panel form-panel panel-primary">
                <div class="panel-body">
                    <form method="post" enctype="multipart/form-data">
                        <div id="form">

                            {% csrf_token %}

                            <div class="form-field form-subtitle col-sm-11">
                                <span> Datos del Producto</span>
                            </div>

                            <div class=" col-sm-6 col-xs-12">

                                <div class="form-group ">
                                    <div class="hidden-span-top form-field col-sm-11">
                                        {{ producto_form.descripcion.errors }}
                                        <div class="input-group">
                                            <span class="input-group-addon glyphicon glyphicon-pencil " ></span>
                                            {{ producto_form.descripcion }}
                                        </div>
                                    </div>
                                </div>

                            </div>


                            <div class="col-sm-6 col-xs-12">

                                <div class="form-group ">
                                    <div class="no-padding-top  form-field col-sm-11">
                                        {{ producto_form.stock_minimo.errors }}
                                        <div class="input-group">
                                            <span class="input-group-addon glyphicon glyphicon-flag " ></span>
                                            {{ producto_form.stock_minimo }}
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group ">
                                    <div class="form-field col-sm-11">
                                        {{ producto_form.categoria.errors }}
                                        <span class="label label-default"> Categoría</span>
                                        <div class="input-group">
                                            <span class="input-group-addon glyphicon glyphicon-tag " ></span>
                                            {{ producto_form.categoria }}
                                        </div>
                                    </div>
                                </div>

                            </div>

                            {{ unidad_producto_formset.management_form }}
                            <div class="form-field form-subtitle col-sm-11">
                                <span> Detalles del Producto</span>
                            </div>

                            {% for unidad_producto_form in unidad_producto_formset %}

                            <div class="formset">

                                <div class=" col-sm-6 col-xs-12">
                                    <div class="form-group ">
                                        <div class="no-padding-top form-field col-sm-11">
                                            <span class="label label-default"> Unidad</span>
                                            {{ unidad_producto_form.id_unidad.errors }}
                                            <div class="input-group">
                                                <span class="input-group-addon glyphicon glyphicon-asterisk " ></span>
                                                {{ unidad_producto_form.id_unidad}}
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                {{ unidad_producto_form.id}}
                                <div class=" hidden-span-top col-sm-6 col-xs-12">

                                    <div class="form-group ">
                                        <div class="no-padding-top form-field col-sm-11">

                                            {{ unidad_producto_form.valor.errors }}
                                            <div class="input-group">
                                                <span class="input-group-addon glyphicon glyphicon-asterisk " ></span>
                                                {{ unidad_producto_form.valor}}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% if unidad_producto_formset.can_delete %}
                                    {{ unidad_producto_form.DELETE }}

                                {% endif %}
                            </div>



                            {% endfor %}





                            <div class="submit-row  col-xs-12">
                                <input  class ="col-sm-offset-2 col-sm-4  col-xs-12 btn btn-success btn-lg" type="submit"
                                    value="Guardar cambios" />
                                <a class ="col-sm-offset-1 col-sm-3  col-xs-12 btn btn-danger btn-lg"
                                   href="{% url 'productos:index' %}">
                                    Volver
                                </a>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/productos/index.html
{% extends 'base.html' %}


{%  block breadcrumb %}
    <ol class="breadcrumb">
        <li ><a href="{%  url 'almacen:index' %}">Inicio</a></li>
        <li class="active">Productos</li>
    </ol>
{% endblock %}

{% block content %}
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
    {% endfor %}
    {% endif %}
    <div class="contenedor-modulos">
        <div class="row">
            <a href="{% url 'productos:Listar_Productos' %}" class="module col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
                <h3>Listar Productos</h3>
            </a>
            <a href="{% url 'productos:Registrar_Producto' %}" class="module col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <span class="glyphicon glyphicon-tag" aria-hidden="true"></span>
                <h3>Registrar Productos</h3>
            </a>
            <a href="{% url 'productos:Categorias' %}" class="module col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                <h3>Gestionar Categorias</h3>
            </a>
            <a class="col-sm-offset-0 col-xs-offset-5 backbutton" href="{% url 'almacen:index' %}">
                <span class="  glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            </a>
        </div>
    </div>

{% endblock %}

templates/productos/listar_productos.html
{% extends 'base.html' %}


{%  block breadcrumb %}
     <ol class="breadcrumb">
        <li ><a href="{%  url 'almacen:index' %}">Inicio</a></li>
        <li class="active"><a href="{%   url 'productos:index' %}">Productos</a></li>
        <li >Listar Productos</li>
    </ol>
{% endblock %}


{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class=" contenedor-lista">
        <div class="panel  panel-primary">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-pencil"></span>
                <span class="">LISTADO DE PRODUCTOS</span>
                <a class ="pull-right btn btn-danger  "
                   href="{% url 'productos:index' %}">Volver
                </a>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table id="datatable-responsive" class="table table-striped ">
                        {% load static from staticfiles %}
                        <thead>
                            <tr  align="center">
                                <th width="5%">Código</th>
                                <th width="15%">Stock Min.</th>
                                <th width="30%">Descripción</th>
                                <th width="20%">Categoría</th>
                                <th width="30%">Operaciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for producto in object_list %}
                            <tr valign="middle" class="{{forloop.counter|divisibleby:2|yesno:'even,odd'}}">
                                <td align="center">{{ producto.codigo }}</td>
                                <td align="center">{{ producto.stock_minimo }}</td>
                                <td align="center">{{ producto.descripcion }}</td>
                                <td align="center">{{ producto.categoria }}</td>
                                <td align="center">
                                    <a href="{% url 'productos:Editar_Producto' producto.codigo %}"
                                       class="btn btn-info">
                                        Editar
                                    </a>
                                    <a href="{% url 'productos:Eliminar_Producto' producto.codigo %}"
                                       data-toggle="modal" data-target="#delete-modal"
                                       class="btn btn-danger btn-delete">
                                        Eliminar
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="modal fade" id="delete-modal">
            <div class="modal-dialog">
                <div class="modal-content">

                </div>
            </div>
        </div>


    </div>
{% endblock %}