Base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from apps.usuarios.views import Login,Logout
from django.conf.urls.static import static
from django.contrib.auth.views import login

urlpatterns = [
   path('admin/', admin.site.urls),
   path('login/', Login.as_view()),
   path('logout/', Logout.as_view()),
   path('',include('apps.almacen.urls', namespace='almacen')),
   url(r'^usuarios/',include('apps.usuarios.urls',namespace='usuarios')),
   url(r'^productos/',include('apps.productos.urls',namespace='productos')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
admin.site.site_header = 'Administrador BACKEND Real Star'
admin.site.site_title= "Interface web del administrador"

apps/almacen/urls.py
from django.urls import path, include
from django.conf.urls import url
from .views import *
app_name = 'index',
app_name='reporte'
#app_name='getProductosfromAlmacen'

urlpatterns = [
	url(r'^$', Index.as_view(),name='index'),
    url(r'^operaciones$', Operaciones.as_view(),name='operaciones'),
	url(r'^operaciones/ingresos$', IngresoView.as_view(),name='ingresos'),
    url(r'^operaciones/reingresos$', Reingresos.as_view(),name='reingresos'),
    url(r'^operaciones/salidas$',SalidaView.as_view(), name='salidas'),

    url(r'^operaciones/listar_ingresos/$',ListarIngresos.as_view(), name='lista_ingresos'),
    url(r'^operaciones/listar_ingresos/(\d+)/$',DetalleIngresoView.as_view(), name='detalle_ingresos'),


    url(r'^operaciones/listar_reingresos$',ListarReingresoView.as_view(), name='lista_reingreso'),
    url(r'^operaciones/listar_reingresos/(\d+)/$$',DetalleReingresoView.as_view(), name='detalle_reingreso'),

    url(r'^operaciones/listar_salidas$',ListarSalidas.as_view(), name='lista_salidas'),
    url(r'^operaciones/listar_salidas/(\d+)/$',DetalleSalidaView.as_view(), name='detalle_salidas'),

    url(r'^operaciones/getproducto/$',getProductosfromAlmacen,name='getProductosfromAlmacen'),
    url(r'^operaciones/getcantidad/(\d+)/(\d+)/$',getCantidadfromProductos,name='getCantidadfromProductos'),
    url(r'^reporte', Reporte.as_view(),name='reporte'),
]

apps/almacen/models.py
from django.db import models
from apps.usuarios.models import User
from apps.productos.models import Producto, UnidadMedicion
from django.utils import timezone


class Proveedor(models.Model):
    ruc = models.CharField(max_length=10,primary_key=True)
    nombre = models.CharField(max_length=30)
    direccion = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = "Proveedores"

    def __str__(self):
        return self.nombre

class GuiaRemision(models.Model):
    fecha_traslado = models.DateField()
    punto_partida = models.CharField(max_length=30)
    nro_guia_remitente = models.CharField(max_length=15)
    placa_vehiculo = models.CharField(max_length=10)
    licencia_conducir = models.CharField(max_length=15)
    proveedor = models.ForeignKey(Proveedor,blank=True,null=True, on_delete=models.PROTECT)

    class Meta:
        verbose_name_plural = "Guias de remision"

    def __str__(self):
        return self.nro_guia_remitente

class Almacen(models.Model):
    ubicacion = models.CharField(max_length=50, blank=True, null=True)
    capacidad = models.IntegerField(blank=True,null=True)
    def __str__(self):
        return self.ubicacion
    class Meta:
        verbose_name_plural = "Almacenes"


class Ingreso(models.Model):
    dni_usuario = models.ForeignKey(User, blank=True, null=True, on_delete=models.PROTECT)
    fecha = models.DateField(default=timezone.now ,blank=True, null=True)
    guia_remision = models.ForeignKey(GuiaRemision, blank=True, null=True, on_delete=models.PROTECT)
    tipo = models.IntegerField(blank=True, null=True) #ingreso :1   , reingreso:2
    almacen = models.ForeignKey(Almacen,blank=True,null=True, on_delete=models.PROTECT)
    class Meta:
        verbose_name = "Ingreso"
        verbose_name_plural = "Ingresos"



class DetalleIngreso(models.Model):
    id_ingreso = models.ForeignKey(Ingreso, blank=True, null=True, on_delete=models.PROTECT)
    codigo_producto = models.ForeignKey(Producto, blank=True, null=True, on_delete=models.PROTECT)
    serie = models.CharField(max_length=20, blank=True, null=True)
    cantidad = models.IntegerField(blank=True, null=True)
    unidad_caja = models.ForeignKey(UnidadMedicion,blank=True, null=True, on_delete=models.PROTECT)
    estado = models.CharField(max_length=15, blank=True, null=True)




class DetalleAlmacen(models.Model):
    codigo_producto = models.ForeignKey(Producto,blank=True,null=True, on_delete=models.PROTECT)
    id_almacen = models.ForeignKey(Almacen,blank=True,null=True, on_delete=models.PROTECT)
    id_ingreso = models.ForeignKey(Ingreso, blank=True, null=True, on_delete=models.PROTECT)
    cantidad = models.IntegerField(blank=True,null=True)
    estado = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        verbose_name = "Detalle de almacen"
        verbose_name_plural = "Detalle de los almacenes"



class Salida(models.Model):
    dni_usuario = models.ForeignKey(User,blank=True,null=True, on_delete=models.PROTECT)
    fecha = models.DateField(blank=True, null=True)
    nodo = models.CharField(max_length=15, blank=True, null=True)
    devolucion = models.NullBooleanField()
    def __str__(self):
        return "Fecha: %s - Nodo: %s" %(self.fecha,self.nodo)
    class Meta:
        verbose_name = "Salida"
        verbose_name_plural = "Salidas"


class DetalleSalida(models.Model):
    id_salida = models.ForeignKey(Salida, blank=True, null=True, on_delete=models.PROTECT)
    id_almacen = models.ForeignKey(Almacen,blank=True, null=True, on_delete=models.PROTECT)
    codigo_producto = models.ForeignKey(Producto,blank=True, null=True, on_delete=models.PROTECT)
    cantidad = models.IntegerField(blank=True, null=True)
    class Meta:
        verbose_name = "Detalles de Salida"
        verbose_name_plural = "Detalles de Salidas"

class DetalleStock(models.Model):
    id_almacen = models.ForeignKey(Almacen,blank=True, null=True, on_delete=models.PROTECT)
    producto = models.ForeignKey(Producto,blank=True, null=True, on_delete=models.PROTECT)
    stock = models.IntegerField(blank=True, null=True)
    class Meta:
        verbose_name = "Stock"
        verbose_name_plural = "Stocks"

apps/almacen/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponseRedirect , redirect, HttpResponse
from django.utils.decorators import method_decorator
from django.views.generic import View, ListView, DeleteView
from django.template.context import RequestContext
from django.http import HttpResponseRedirect
from Base.mixins import SuccessMessageMixin
from .forms import *
from .models import Ingreso,DetalleIngreso,Salida,DetalleAlmacen,DetalleStock
from django.views.generic.detail import DetailView

class LoginRequiredMixin(object):
    u"""Ensures that user must be authenticated in order to access view."""

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)

class Index(LoginRequiredMixin, View):

    template_name = 'almacen/index.html'
    def get(self, request):
        return render(request, self.template_name)

class Operaciones(LoginRequiredMixin,View):
    template_name='almacen/operaciones/index.html'
    def get(self,request):
        return render(request,self.template_name)

class IngresoView(LoginRequiredMixin,SuccessMessageMixin,View):

    template_name = 'almacen/ingresos/index.html'
    model = Ingreso

    def get(self,request):
        ingresos_form= IngresoForm
        formset = DetalleIngresoFormSet(prefix='formset')
        guiaremision_form = GuiaRemisionForm

        return render(request,self.template_name,locals())

    def post(self,request):

        ingresos_form= IngresoForm(request.POST)
        guiaremision_form = GuiaRemisionForm(request.POST)

        if ingresos_form.is_valid() and guiaremision_form.is_valid():
            nuevo_ingreso = ingresos_form.save(commit=False)
            nuevo_ingreso.dni_usuario = request.user
            nuevo_ingreso.tipo = 1
            nuevo_ingreso.guia_remision = guiaremision_form.save()
            nuevo_ingreso.save()
            detalle_ingreso = DetalleIngresoFormSet(request.POST,prefix='formset',instance=nuevo_ingreso,)

            if detalle_ingreso.is_valid():
                for detalle in detalle_ingreso.save(commit=False):
                    detalle.id_almacen = Almacen.objects.get(id=request.POST['almacen'])
                detalle_ingreso.save()
                success_message = 'Los datos se actualizaron correctamente'
                InsertarDetalleAlmacen(nuevo_ingreso.id,request.POST['almacen'])
                return redirect("/operaciones/listar_ingresos/")
            return render(request,self.template_name,locals())
        else:
            return render(request,self.template_name,locals())



class Reingresos(LoginRequiredMixin,View):

    template_name = 'almacen/reingresos/index.html'
    model = Ingreso

    def get(self,request):
        ingresos_form= IngresoForm
        formset = DetalleIngresoFormSet(prefix='formset')

        return render(request,self.template_name,locals())

    def post(self,request):

        ingresos_form= IngresoForm(request.POST)

        if ingresos_form.is_valid() :
            nuevo_ingreso = ingresos_form.save(commit=False)
            nuevo_ingreso.dni_usuario = request.user
            nuevo_ingreso.tipo = 2
            nuevo_ingreso.save()

            detalle_ingreso = DetalleIngresoFormSet(request.POST,prefix='formset',instance=nuevo_ingreso)

            if detalle_ingreso.is_valid():

                for detalle in detalle_ingreso.save(commit=False):
                    detalle.id_almacen = Almacen.objects.get(id=request.POST['almacen'])

                detalle_ingreso.save()
                InsertarDetalleAlmacen(nuevo_ingreso.id,request.POST['almacen'])
                success_message = 'Los datos se actualizaron correctamente'
                return redirect("/operaciones/listar_reingresos")

        return render(request,self.template_name,locals())

class ListarReingresoView(LoginRequiredMixin,View):
    def get(self,request):
        object_list = Ingreso.objects.filter(tipo=2)
        template_name = 'almacen/reingresos/lista_reingresos.html'
        return render(request,template_name,locals())

class DetalleReingresoView(LoginRequiredMixin,View):
    def get(self,request,id):
        object_list = Ingreso.objects.filter(tipo=2)
        sal = Ingreso.objects.get(pk=id)
        det = DetalleIngreso.objects.filter(id_ingreso=id)
        template_name = 'almacen/reingresos/lista_reingresos.html'
        status = True
        return render(request,template_name,locals())

class ListarIngresos(LoginRequiredMixin,ListView):
    def get(self,request):
        object_list = Ingreso.objects.filter(tipo=1)
        template_name = 'almacen/ingresos/lista_ingresos.html'
        return render(request,template_name,locals())


class DetalleIngresoView(LoginRequiredMixin,View):
    def get(self,request,id):
        object_list = Ingreso.objects.filter(tipo=1)
        sal = Ingreso.objects.get(pk=id)
        det = DetalleIngreso.objects.filter(id_ingreso=id)
        template_name = 'almacen/ingresos/lista_ingresos.html'
        status = True
        return render(request,template_name,locals())

#SALIDAS
import datetime

class SalidaView(LoginRequiredMixin,View,SuccessMessageMixin):
    template_name = 'almacen/salidas/index.html'
    def get(self, request):
        salidaform = SalidaForm
        formset = DetalleSalidaFormset(prefix='formset')
        #Verificar stock minimo
        stock = DetalleStock.objects.all()
        prod_list = []
        for item in stock:
            if item.stock < item.producto.stock_minimo:
                prod_list.append({'nombre':item.producto.descripcion, 'cantidad':item.stock,'almacen': item.id_almacen.ubicacion})
        print (prod_list)
        if prod_list.__len__() >0:
            return render(request,self.template_name,{'salidaform':salidaform,'formset':formset,'prod_list':prod_list,'status':True})
        else:
            return render(request,self.template_name,{'salidaform':salidaform,'formset':formset})
    def post(self,request):
        salidaform = SalidaForm(request.POST)
        if salidaform.is_valid() :
            salida = salidaform.save(commit=False)
            salida.fecha = datetime.date.today()
            salida.save()
            formset = DetalleSalidaFormset(request.POST,prefix='formset',instance=salida)
            if formset.is_valid():
                for detalle in formset.save(commit=False):
                    ActualizarSalida(detalle.id_almacen,detalle.codigo_producto,detalle.cantidad)
                formset.save()
                return  HttpResponseRedirect("/operaciones/listar_salidas")
            else:
                return render(request,self.template_name,locals())

        else:
            formset = DetalleSalidaFormset(request.POST,prefix="formset")
            return render(request, self.template_name,{'salidaform': salidaform,'formset':formset})

class DetalleSalidaView(LoginRequiredMixin,View):
    def get(self,request,id):
        object_list = Salida.objects.all()
        sal = Salida.objects.get(pk=id)
        det = DetalleSalida.objects.filter(id_salida=id)
        template_name = 'almacen/salidas/lista_salidas.html'
        status = True
        return render(request,template_name,locals())


class ListarSalidas(LoginRequiredMixin,ListView):
    model = Salida
    template_name = 'almacen/salidas/lista_salidas.html'

class EliminarSalida(SuccessMessageMixin,DeleteView):
    model = Salida
    success_url = '/operaciones/listar_salidas'
    template_name = 'almacen/salidas/confirm_delete_salida.html'
    success_message = 'El registro de salida fue eliminado correctamente'






#Funcion que se usa despues de cada ingreso(o reingreso) para insertar un registro en detallealmacen, y actualizar el stock
def InsertarDetalleAlmacen(ingreso_id,almacen_id):
    for p in DetalleIngreso.objects.filter(id_ingreso = ingreso_id).distinct():
        objeto = DetalleIngreso.objects.filter(id_ingreso = ingreso_id, codigo_producto = p.codigo_producto.codigo)
        cantidad = 0
        for r in objeto:
            cantidad = cantidad +  r.cantidad
        nuevo = DetalleAlmacen()
        nuevo.codigo_producto = Producto.objects.get(pk=p.codigo_producto.codigo)
        nuevo.id_almacen = Almacen.objects.get(pk=almacen_id)
        nuevo.id_ingreso = Ingreso.objects.get(pk=ingreso_id)
        nuevo.cantidad = cantidad
        nuevo.save()
        update = DetalleStock.objects.filter(id_almacen=almacen_id).filter(producto=p.codigo_producto.codigo)
        for item in update:
                item.stock = item.stock + cantidad
                item.save()
        if len(update) == 0:
            objeto = DetalleStock()
            objeto.id_almacen = Almacen.objects.get(pk=almacen_id)
            objeto.producto = Producto.objects.get(pk=p.codigo_producto.codigo)
            objeto.stock = cantidad
            objeto.save()

#Funcion que se utiliza para actualizar el stock luego de una salida
def ActualizarSalida(almacen_id,producto_id,cantidad):
    lista = DetalleStock.objects.filter(id_almacen = almacen_id).filter(producto = producto_id)
    print (lista)
    for item in lista:
        item.stock = item.stock - cantidad
        item.save()

#SOLO PARA PRUEBAS
class ActualizarStock:
    almacen = 0
    def __init__(self,almacen):
        self.almacen = int(almacen)
    def ActualizarTodoStock(self):
        stock = []
        for p in Producto.objects.all():
            contador = 0
            lista = DetalleAlmacen.objects.filter(id_almacen=self.almacen).filter(codigo_producto=p.codigo)
            for c in lista:
                contador = contador + c.cantidad
            if contador>0:
                stock.append((p.codigo,contador))
                d = DetalleStock.objects.filter(id_almacen=self.almacen).filter(producto=p)
                for item in d:
                    item.stock = contador
                    item.save()
                if len(d) == 0:

templates/almacen/salidas/lista_salidas.html
{% extends 'base.html' %}


{%  block breadcrumb %}
     <ol class="breadcrumb">
        <li ><a href="{%  url 'almacen:index' %}">Inicio</a></li>
        <li class="active"><a href="{%   url 'almacen:operaciones' %}">Almacén</a></li>
        <li >Listar Salidas</li>
    </ol>
{% endblock %}


{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class=" contenedor-lista">
        <div class="panel  panel-primary">
            <div class="panel-heading">
                <ul class="nav nav-tabs nav-justified">
                     <li role="presentation" ><a href="{% url 'almacen:salidas' %}">Registro de Salidas</a></li>
                     <li role="presentation" class="active"><a href="{% url 'almacen:lista_salidas' %}">Listado de Salidas</a></li>
                 </ul>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table id="datatable-responsive" class="table table-striped ">
                        {% load static from staticfiles %}
                        <thead>
                            <tr  align="center">
                                <th width="10%">Fecha</th>
                                <th width="20%">Trabajador</th>
                                <!--<th width="20%">Almacen</th>-->
                                <th width="20%">Nodo</th>
                                <th width="10%">Devolucion</th>
                                <th width="40%">Operaciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for salida in object_list %}
                            <tr valign="middle" class="{{forloop.counter|divisibleby:2|yesno:'even,odd'}}">
                                <td align="center">{{ salida.fecha }}</td>
                                <td align="center">{{ salida.dni_usuario }}</td>
                                <td align="center">{{ salida.nodo }}</td>
                                <td align="center">{% if salida.devolucion%}
                                        <span class="glyphicon glyphicon-ok-circle" ></span>
                                    {% else %}
                                        <span class="glyphicon glyphicon-remove-circle" ></span>
                                    {% endif %}
                                    </td>
                                <td align="center">
                                    <a href="{% url 'almacen:detalle_salidas' salida.id %}"
                                       class="btn btn-info">
                                        Detalles
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="modal fade" id="delete-modal">
            <div class="modal-dialog">
                <div class="modal-content">

                </div>
            </div>
        </div>


    </div>
    {% if status %}
        <style>
        .modal-header {
            padding:9px 15px;
            border-bottom:1px solid #eee;
            background-color: #0480be;
            color : white;
            -webkit-border-top-left-radius: 5px;
            -webkit-border-top-right-radius: 5px;
            -moz-border-radius-topleft: 5px;
            -moz-border-radius-topright: 5px;
             border-top-left-radius: 5px;
             border-top-right-radius: 5px;
         }
        </style>
        <!-- Modal HTML -->
            <div id="detalle" class="modal fade">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title"><strong>Detalle de Salida Nro. {{ sal.id }}</strong></h4>
                        </div>
                        <div class="modal-body">
                            <table width="100%">
                                <tr >
                                    <td><STRONG>Trabajador</STRONG></td>
                                    <td>{{ sal.dni_usuario }}</td>
                                </tr>
                                <tr >
                                    <td><STRONG>Fecha</STRONG></td>
                                    <td>{{ sal.fecha }}</td>
                                </tr>
                                <tr >
                                    <td><STRONG>Motivo</STRONG></td>
                                    <td>{% if sal.devolucion %}
                                        Devolución de productos defectuosos al proveedor.
                                    {% else %}
                                        Productos empleados para el Nodo {{ sal.nodo }}.
                                    {% endif %}</td>
                                </tr>
                            </table>
                            <br>
                            <table class="table table-bordered">
                                <thead>
                                    <th>Almacen</th>
                                    <th>Producto</th>
                                    <th>Cantidad</th>
                                </thead>
                                {% for d in det %}
                                <tr>
                                    <td>{{ d.id_almacen }}</td>
                                    <td>{{ d.codigo_producto }}</td>
                                    <td>{{ d.cantidad }}</td>
                                </tr>
                                {% endfor %}
                            </table>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-success" data-dismiss="modal"><span class="glyphicon glyphicon-ok"> Aceptar</span></button>
                        </div>
                    </div>
                </div>
            </div>

    {% endif %}
    {% endblock %}