Base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from apps.usuarios.views import Login,Logout
from django.conf.urls.static import static
from django.contrib.auth.views import login

urlpatterns = [
   path('admin/', admin.site.urls),
   path('login/', Login.as_view()),
   path('logout/', Logout.as_view()),
   path('',include('apps.almacen.urls', namespace='almacen')),
   url(r'^usuarios/',include('apps.usuarios.urls',namespace='usuarios')),
   url(r'^productos/',include('apps.productos.urls',namespace='productos')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
admin.site.site_header = 'Administrador BACKEND Real Star'
admin.site.site_title= "Interface web del administrador"

apps/almacen/urls.py
from django.urls import path, include
from django.conf.urls import url
from .views import *
app_name = 'index',
app_name='reporte'
#app_name='getProductosfromAlmacen'

urlpatterns = [
	url(r'^$', Index.as_view(),name='index'),
    url(r'^operaciones$', Operaciones.as_view(),name='operaciones'),
	url(r'^operaciones/ingresos$', IngresoView.as_view(),name='ingresos'),
    url(r'^operaciones/reingresos$', Reingresos.as_view(),name='reingresos'),
    url(r'^operaciones/salidas$',SalidaView.as_view(), name='salidas'),

    url(r'^operaciones/listar_ingresos/$',ListarIngresos.as_view(), name='lista_ingresos'),
    url(r'^operaciones/listar_ingresos/(\d+)/$',DetalleIngresoView.as_view(), name='detalle_ingresos'),


    url(r'^operaciones/listar_reingresos$',ListarReingresoView.as_view(), name='lista_reingreso'),
    url(r'^operaciones/listar_reingresos/(\d+)/$$',DetalleReingresoView.as_view(), name='detalle_reingreso'),

    url(r'^operaciones/listar_salidas$',ListarSalidas.as_view(), name='lista_salidas'),
    url(r'^operaciones/listar_salidas/(\d+)/$',DetalleSalidaView.as_view(), name='detalle_salidas'),

    url(r'^operaciones/getproducto/$',getProductosfromAlmacen,name='getProductosfromAlmacen'),
    url(r'^operaciones/getcantidad/(\d+)/(\d+)/$',getCantidadfromProductos,name='getCantidadfromProductos'),
    url(r'^reporte', Reporte.as_view(),name='reporte'),
]

apps/usuarios/urls.py
from django.conf.urls import url

from .views import Configuracion, RegistrarTrabajador,ListarTrabajadores,EditarTrabajador,EliminarTrabajador,Prueba
app_name='usuarios'
urlpatterns = [
	url(r'^$', Configuracion.as_view(),name='index'),
    url(r'^nuevo/$', RegistrarTrabajador.as_view(),name='add_trabajador'),
    url(r'^lista/$', ListarTrabajadores.as_view(),name='trabajadores_list'),
    url(r'^editar/(?P<pk>\d+)/$', EditarTrabajador.as_view(),name='trabajador_detail'),
    url(r'^eliminar/(?P<pk>\d+)/$', EliminarTrabajador.as_view(),name='trabajador_delete'),
]

templates/configuracion/confirm_delete_trabajador.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title"> Advertencia</h4>
</div>
<div class="modal-body">
    <form action="{% url 'usuarios:trabajador_delete' object.id%}" class="text-center"method="post">{% csrf_token %}
        <p>Esta seguro que desea eliminar a {{ object.first_name }} {{ object.last_name }} de la base de datos ?</p>
        <input class="btn btn-success" type="submit" value="Si, estoy seguro" />
    </form>
</div>

templates/configuracion/editar_trabajador.html
{% extends 'base.html' %}

{%  block breadcrumb %}
     <ol class="breadcrumb">
        <li ><a href="{%  url 'almacen:index' %}">Inicio</a></li>
        <li class="active"><a href="{%   url 'usuarios:index' %}">Configuración</a></li>
        <li >Editar Trabajador</li>
    </ol>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">

                <form  method="post">{% csrf_token %}
                    <div class="form-group ">
                        <div class="form-field col-sm-offset-2 col-xs-offset-1 col-sm-8 col-xs-10">
                            {{ form.username.errors }}
                            <label class="form-label" for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
                            <div class="input-group">
                                <span class="input-group-addon glyphicon glyphicon-user"></span>
                                {{ form.username }}
                            </div>
                        </div>
                    </div>

                    <div class="form-group ">
                        {{ form.email.errors }}
                        <div class="form-field col-sm-offset-2 col-xs-offset-1 col-sm-8 col-xs-10">
                            <label class="form-label" for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                            <div class="input-group">
                                <span class="input-group-addon ">@</span>
                                {{ form.email }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group ">
                        {{ form.first_name.errors }}
                        <div class="form-field col-sm-offset-2 col-xs-offset-1 col-sm-8 col-xs-10">
                            <label class="form-label" for="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}</label>
                            <div class="input-group">
                                <span class="input-group-addon glyphicon glyphicon-user"></span>
                                {{ form.first_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group ">
                        <div class="form-field col-sm-offset-2 col-xs-offset-1 col-sm-8 col-xs-10">
                            {{ form.last_name.errors }}
                            <label class="form-label" for="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}</label>
                            <div class="input-group">
                                <span class="input-group-addon glyphicon glyphicon-user"></span>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group ">
                        <div class="form-field col-sm-offset-2 col-xs-offset-1 col-sm-8 col-xs-10">
                            {{ form.dni.errors }}
                            <label class="form-label" for="{{ form.dni.id_for_label }}">{{ form.dni.label }}</label>
                            <div class="input-group">
                                <span class="input-group-addon glyphicon glyphicon-pencil"></span>
                                {{ form.dni }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group ">
                        <div class="form-field col-sm-offset-2 col-xs-offset-1 col-sm-8 col-xs-10">
                            {{ form.cellphone.errors }}
                            <label class="form-label" for="{{ form.cellphone.id_for_label }}">{{ form.cellphone.label }}</label>
                            <div class="input-group">
                                <span class="input-group-addon glyphicon glyphicon-phone"></span>
                                {{ form.cellphone }}
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="form-field col-sm-offset-2 col-xs-offset-1 col-sm-8 col-xs-10">
                            <div class="btn-group" data-toggle="buttons">
                              <label class="btn btn-primary {% if form.is_active.value %} active {% endif %}">
                                {{ form.is_active }} {{ form.is_active.label }}
                              </label>
                              <label class="btn btn-warning {% if form.is_staff.value %} active {% endif %}">
                               {{ form.is_staff }} {{ form.is_staff.label }}
                              </label>
                            </div>
                        </div>
                    </div>


                    <div class="form-group action-buttons">
                        <div class="form-field col-sm-offset-2 col-xs-offset-1 col-sm-8 col-xs-10">
                            <input  class ="col-xs-12 col-sm-6 btn btn-success btn-lg" type="submit"
                                    value="Guardar Cambios" />
                            <a href="{% url 'usuarios:trabajadores_list' %}"
                               class ="col-sm-push-1 col-sm-5 col-xs-12 btn btn-danger btn-lg" >
                                Volver
                            </a>
                        </div>
                    </div>


                </form>
        </div>

    </div>

{% endblock %}

templates/configuracion/index.html
{% extends 'base.html' %}

{%  block breadcrumb %}
    <ol class="breadcrumb">
        <li ><a href="{%  url 'almacen:index' %}">Inicio</a></li>
        <li class="active">Configuración</li>
    </ol>
{% endblock %}

{% block content %}
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
    {% endfor %}
    {% endif %}
    <div class="contenedor-modulos">
        <div class="row">
            <a href="{% url 'usuarios:add_trabajador' %}" class="module col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                <h3>Registrar Trabajador</h3>
            </a>
            <a href="{% url 'usuarios:trabajadores_list' %}" class="module col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                <h3>Lista de Trabajadores</h3>
            </a>
            <a class="col-sm-offset-0 col-xs-offset-5 backbutton" href="{% url 'almacen:index' %}">
                <span class="  glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            </a>

        </div>
    </div>

{% endblock %}

templates/configuracion/listar_trabajadores.html
{% extends 'base.html' %}

{%  block breadcrumb %}
     <ol class="breadcrumb">
        <li ><a href="{%  url 'almacen:index' %}">Inicio</a></li>
        <li class="active"><a href="{%   url 'usuarios:index' %}">Configuración</a></li>
        <li >Listar Trabajadores</li>
    </ol>
{% endblock %}


{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class=" contenedor-lista">
        <div class="panel  panel-primary">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-pencil"></span>
                <span class="">LISTADO DE TRABAJADORES</span>
                <a class ="pull-right btn btn-success  "
                   href="{% url 'usuarios:add_trabajador' %}">Volver
                </a>
                <a class ="pull-right btn btn-danger  "
                   href="{% url 'usuarios:index' %}">Volver
                </a>
            </div>
            <div class="panel-body">
                <div  class="table-responsive">
                    <table id="datatable-responsive" class="table table-striped ">
                        {% load static from staticfiles %}
                        <thead>
                        <tr  align="center">
                            <th width="5%">DNI</th>
                            <th width="30%">NOMBRES</th>
                            <th width="30%">APELLIDOS</th>
                            <th width="8%">TELEFONO</th>
                            <th width="27%">ACCIONES</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for trabajador in object_list %}
                                <tr valign="middle" class="{{forloop.counter|divisibleby:2|yesno:'even,odd'}}">
                                    <td align="center">{{ trabajador.dni }}</td>
                                    <td align="center">{{trabajador.first_name}}</td>
                                    <td align="center">{{trabajador.last_name}}</td>
                                    <td align="center">{{trabajador.cellphone}}</td>
                                    <td align="center">
                                        <a href="{% url 'usuarios:trabajador_detail' trabajador.id %}"
                                           class="btn btn-info">Editar</a>
                                        <a href="{% url 'usuarios:trabajador_delete' trabajador.id %}"
                                           data-toggle="modal" data-target="#delete-modal"
                                           class="btn btn-danger btn-delete">Eliminar</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

     </div>

{#        <a class="col-sm-offset-0 col-xs-offset-4 backbutton" href="{% url 'usuarios:index' %}">#}
{#            <span class="  glyphicon glyphicon-chevron-left" aria-hidden="true"></span>#}
{#        </a>#}

        <div class="modal fade" id="delete-modal">
            <div class="modal-dialog">
                <div class="modal-content">

                </div>
            </div>
        </div>


    </div>
{% endblock %}

templates/configuracion/nuevo_trabajador.html
{% extends 'base.html' %}


{%  block breadcrumb %}
     <ol class="breadcrumb">
        <li ><a href="{%  url 'almacen:index' %}">Inicio</a></li>
        <li class="active"><a href="{%   url 'usuarios:index' %}">Configuración</a></li>
        <li >Registrar Trabajador</li>
    </ol>
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="panel form-panel panel-primary">
                <div class="panel-body">
                    <form action="" method="post">{% csrf_token %}
                        <div class="credenciales col-sm-6 col-xs-12">
                            <div class="form-field  form-subtitle col-sm-11">
                                <span>Credenciales</span>
                            </div>
                            <div class="form-group ">
                                <div class="form-field col-sm-11 " >
                                    {{ form.username.errors }}
                                    <div class="input-group">
                                        <span class="input-group-addon glyphicon glyphicon-user"></span>
                                        {{ form.username }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group ">
                                <div class="form-field col-sm-11">
                                    {{ form.password.errors }}
                                    <div class="input-group">
                                        <span class="input-group-addon glyphicon glyphicon-lock" ></span>
                                        {{ form.password }}
                                    </div>

                                </div>
                            </div>
                            <div class="form-group ">
                                <div class="form-field col-sm-11  ">
                                    {{ form.password.errors }}
                                    <div class="input-group">
                                        <span class="input-group-addon glyphicon glyphicon-lock" ></span>
                                        <input class="form-control" placeholder="Confirme Contraseña" id="id_password2"
                                           name="password2" type="password" required>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group ">

                                <div class="form-field col-sm-11 ">
                                    {{ form.email.errors }}
                                    <div class="input-group">
                                        <span class="input-group-addon " >@</span>
                                        {{ form.email }}
                                        </div>
                                </div>
                            </div>
                        </div>


                        <div class="datos col-sm-6 col-sm-12">
                            <div class="form-field form-subtitle col-sm-11">
                                <span> Datos Personales</span>
                            </div>
                            <div class="form-group ">
                                <div class="form-field col-sm-11">
                                    {{ form.first_name.errors }}
                                    <div class="input-group">
                                        <span class="input-group-addon glyphicon glyphicon-user " ></span>
                                        {{ form.first_name }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group ">
                                <div class="form-field col-sm-11">
                                    {{ form.last_name.errors }}
                                    <div class="input-group">
                                        <span class="input-group-addon glyphicon glyphicon-user " ></span>
                                        {{ form.last_name }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group ">
                                <div class="form-field col-sm-11">
                                    {{ form.dni.errors }}
                                    <div class="input-group">
                                        <span class="input-group-addon glyphicon glyphicon-pencil" > </span>
                                        {{ form.dni }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group ">
                                <div class="form-field col-sm-11">
                                    {{ form.cellphone.errors }}
                                    <div class="input-group">
                                        <span class="input-group-addon glyphicon glyphicon-phone " ></span>
                                        {{ form.cellphone }}
                                    </div>
                                </div>
                            </div>
                        </div>


                        <div class="submit-row  col-xs-12">
                            <input  id='registrartrabajador' class ="col-sm-offset-2 col-sm-4  col-xs-12 btn btn-success btn-lg" type="submit"
                                    value="Registrar Trabajador" />
                            <a class ="col-sm-offset-1 col-sm-3  col-xs-12 btn btn-danger btn-lg"
                               href="{% url 'usuarios:index' %}">Volver</a>
{#                            <input  class ="col-sm-offset-1 col-sm-3  col-xs-11 btn btn-danger btn-lg" type="submit" value="Volver" />#}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}